name: Build and deploy Node.js app to Azure Web App - ap-hello-cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BE2854E7B8EB4BB49B84362DE57BC77A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA064EC046144BE584EE434B6ABA832A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_85CA6888B69A4F148384B692720D8D7F }}

      - name: Enable build during deployment (Oryx)
        run: |
          az webapp config appsettings set \
            --name ap-hello-cloud \
            --resource-group rg-hello-cloud \
            --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ap-hello-cloud'
          slot-name: 'Production'
          package: .   # ← el repo tal cual; Azure hará npm install y ejecutará "start"
